### PR TITLE
New order endpoints

### PR DESCRIPTION
**Pull request by JacobPlaster**
### Description:
This pull request adds helper functions to interact with the newly added endpoints to the v2 rest Bitfinex API. Also some older funding endpoints seemed to be missing so I have added those in as well.

### Breaking changes:
None

### New Functions:
- `Rest.Funding.Offers`
- `Rest.Funding.OfferHistory`
- `Rest.Funding.Loans`
- `Rest.Funding.LoanHistory`
- `Rest.Funding.Credits`
- `Rest.Funding.CreditHistory`
- `Rest.Funding.Trades`
- `Rest.Funding.SubmitOffer`
- `Rest.Funding.CancelOffer`
- `Rest.Orders.SubmitOrder`
- `Rest.Orders.CancelOrder`
- `Rest.Orders.SubmitUpdateOrder`
- `Rest.Orders.SubmitCancelOrder`
- `Rest.Positions.Claim`
- `Rest.Wallet.Transfer`
- `Rest.Wallet.DepositAddress`
- `Rest.Wallet.CreateDepositAddress`
- `Rest.Wallet.Withdraw`
- `Ws.SubmitFundingOffer`
- `Ws.SubmitFundingCancel`

### Fixes:
None

### PR status:
- [x] Version bumped
- [x] Change-log updated

### CODE REVIEW

**Comment by andreygrehov** [comment]
Calling `Rest.Wallet.DepositAddress` results to a

```
(*bitfinex.Notification)(0xc0000b81e0)({
 MTS: (int64) 1574137008828,
 Type: (string) (len=7) "acc_dep",
 MessageID: (int64) 0,
 NotifyInfo: (interface {}) <nil>,
 Code: (int64) 0,
 Status: (string) (len=7) "SUCCESS",
 Text: (string) (len=7) "success"
})
```

Is this a bug or am I doing something wrong?

**Comment by JacobPlaster** [comment]
Hey @andreygrehov, the response is correct. The payload of the notification `NotifyInfo` contains the data that you are looking for.

**Comment by andreygrehov** [comment]
@JacobPlaster but `NotifyInfo` is nil.

**Comment by andreygrehov** [comment]
@JacobPlaster up

**Comment by JacobPlaster** [comment]
Fixed in https://github.com/bitfinexcom/bitfinex-api-go/pull/203

**Pull request merged**
