### PR TITLE
Adding LedgerService

### PR DESCRIPTION
**Pull request by remco-remco**
- v2/rest: adds support for ledger endpoint

### CODE REVIEW

**Comment by JacobPlaster** [comment]
Hey @remco-remco, thanks for opening a PR, this all looks good. Could you please squash the commits and add a meaningful commit message such as `rest: adds support for ledger endpoint`?

**Comment by remco-remco** [comment]
> Hey @remco-remco, thanks for opening a PR, this all looks good. Could you please squash the commits and add a meaningful commit message such as `v2/rest: adds support for ledger endpoint`?

Hi Jacob, thanks!
I'm very new to github and a bit new to golang.

I also tried to add an example how to use the ledgerservice. it works perfectly on my local pc but i fails testing on github, I decided to remove the example for the moment.

**Comment by JacobPlaster** [comment]
@remco-remco ok thats no problem. This repo uses travis as a build gateway and runs the following commands `golangci-lint run` and `go test -v ./...` whenever you open a push a new commit. If either of these fail then the build will fail and you will get that horrible red cross.

When pushing new changes run `golangci-lint run` and `go test -v ./...` and if they pass locally then the build will pass on travis.

**Comment by remco-remco** [comment]
> @remco-remco ok thats no problem. This repo uses travis as a build gateway and runs the following commands `golangci-lint run` and `go test -v ./...` whenever you update your PR. If either of these fail then the build will fail and you will get that horrible red cross.
> 
> When pushing new changes run `golangci-lint run` and `go test -v ./...` and if they pass locally then the build will pass on travis.

Ok, thanks!

**Comment by remco-remco** [comment]
I have nothing else to add at the moment.
Hope everything looks good for implementation :-)

**Comment by JacobPlaster** [comment]
Looks fine @remco-remco, Im just going to manually test this and ill pass it on to get merged. Thanks again for the work!

**Comment by remco-remco** [comment]
> Looks fine @remco-remco, Im just going to manually test this and ill pass it on to get merged. Thanks again for the work!

Excellent! I'm already using this new function in one of my apps. 
So far it works great.

Thank you too for helping me with this merge!

**Pull request merged**
