### PR TITLE
Refactor v2

### PR DESCRIPTION
**Pull request by brobits**
V2 API refactor to clean up circular dependencies & shared packages.  Currently WIP

### CODE REVIEW

**Comment by phemmer** [comment]
Just my own $0.02:
All the `*FromRaw` functions should go away. They just complicate the code, and they're not idiomatic go. The types should instead satisfy the [`json.Unmarshaller`](https://golang.org/pkg/encoding/json/#Unmarshaler) interface and be unmarshalled onto directly. I did this on my own fork and the code is about 400 lines shorter after ripping it all out.

**Comment by brobits** [comment]
Thanks for the great feedback.  I agree the `fromRaw` functions are not idiomatic go, which is desirable.  I'm still working through this PR and haven't gotten around to refactoring the private/public websocket pumps.  I'll take a look at your suggestion, thank you for the heads up.

**Comment by brobits** [comment]
Could you point me to your fork's changes for the `fromRaw` functions?  I can't seem to find your refactor on the [fix-v2-websocket-response](https://github.com/phemmer/bitfinex-api-go/blob/fix-v2-websocket-response/v2/websocket_private.go#L34-L247) or [master](https://github.com/phemmer/bitfinex-api-go/blob/master/v2/websocket_private.go#L34-L247) branches

**Comment by brobits** [comment]
FYI- rewrote the git history to cleanup excessive git commits during the refactor

**Pull request merged**
