### PR TITLE
rest v2 more endpoints and corrections

### PR DESCRIPTION
**Pull request by flocrok**
v2 rest : corrections on platform_status and client 
             add of candles and tickers public end points

### CODE REVIEW

**Comment by omani** [comment]
nice. just what I needed. thank you.

**Comment by cgebe** [comment]
Why is this still not merged?

**Comment by omani** [comment]
because bitfinex has problems. no time to code.

**Comment by flocrok** [comment]
The pull request #115 has used this work and been merged

**Pull request closed without merging**
